### ISSUE TITLE
Alerts aren't working, but other websites are able to load

### ISSUE THREAD

**Issue by rightpad** [fzwoch/obs-webkitgtk#6]
I've tried from multiple providers (Twitch & StreamElements), and verified that simulated events are correctly being triggered by having them play in a separate browser outside of OBS (Firefox). Full websites will load, but the alert element URLs never play.

OS: Fedora 39
OBS Version: 30.0.0-rc2 (64-bit)

`obs-studio-plugin-webkitgtk` version: 0~git20231023.3c0978b

**Comment by fzwoch** [comment]
![image](https://github.com/fzwoch/obs-webkitgtk/assets/439605/cf6af521-1e2e-4349-bb42-7a6c0e09ef0f)

Works with Streamlabs at least. Perhaps check if no proprietary codecs are being used on the alerts?

**Comment by rightpad** [comment]
No proprietary codecs as far as I can tell. When I looked in the firefox webdev tools, the audio is coming through as a wav, and all the animations are HTML/CSS based. I also noticed that the WebKitGTK sources do not appear in the audio mixer as a source to adjust levels. Does the plugin have the capability of playing audio?

**Comment by fzwoch** [comment]
No, there is no audio support.

**Comment by rightpad** [comment]
Thanks. Seeing how I wasn't able to get the plugin working and there's no audio support, I've decided to use a build of OBS built with the included browser-source plugin at compile time. I appreciate the help with diagnosing the issue, best of luck with the project.
